FROM jenkins/jenkins:lts

USER root

# Install git, docker cli, curl
RUN apt-get update && \
    apt-get install -y git docker.io curl && \
    apt-get clean

# Add jenkins user to docker group
RUN groupadd docker || true && usermod -aG docker jenkins

USER jenkins
