apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins

  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest
    workingDir: /home/jenkins/agent

  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
      - /busybox/sh
    args:
      - -c
      - cat
    tty: true
    volumeMounts:
      - name: docker-config
        mountPath: /kaniko/.docker

  volumes:
  - name: docker-config
    secret:
      secretName: dockerhub-secret
